baseurl = "http://sigir.jp/"

DefaultContentLanguage = "ja"
hasCJKLanguage = true
title = "ACM SIGIR 東京支部"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  etitle = "Tokyo ACM SIGIR Chapter"
  subtitle = ""
  logo = "img/sigir-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "2006年1月2日"
  commit = false
  rss = true
  comments = false
  #readingTime = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[Author]
  name = "ACM SIGIR 東京支部"
  website = ""
  email = "sigir-tokyo@googlegroups.com"
  facebook = "acmsigirtokyo"
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  #github = "username"
  #gitlab = "username"
  twitter = "acmsigirtokyo"
  #reddit = "username"
  #linkedin = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"

[taxonomies]
    tag = "tags"

[[menu.main]]
    identifier = "about"
    name = "About"
    weight = 1

[[menu.main]]
    parent = "about"
    name = "東京支部について"
    url = "page/about/"
    weight = 2

[[menu.main]]
    parent = "about"
    name = "About Tokyo Chapter"
    url = "page/en/about/"
    weight = 3

[[menu.main]]
    parent = "about"
    name = "支部規約"
    url = "page/bylaw/"
    weight = 4

[[menu.main]]
    parent = "about"
    name = "役員"
    url = "page/organization/"
    weight = 5

[[menu.main]]
    identifier = "news"
    name = "News"
    url = "tags/news/"
    weight = 2

[[menu.main]]
    identifier = "events"
    name = "イベント"
    url = "tags/イベント/"
    weight = 3

[[menu.main]]
    identifier = "members"
    name = "会員登録"
    url = "page/registration/"
    weight = 4
